export const calculators = ref([
  {
    id: 'mortgage',
    title: 'Ипотечный калькулятор',
    icon: 'real_estate_agent',
    description: 'Рассчитайте ежемесячный платеж и переплату по ипотеке',
    component: 'MortgageCalc',
    color: 'primary',
  },
  {
    id: 'installment',
    title: 'Рассрочка',
    icon: 'credit_score',
    description: 'Расчет платежей по рассрочке на недвижимость',
    component: 'InstalmentCalc',
    color: 'secondary',
  },
  {
    id: 'rental',
    title: 'Доходность аренды',
    icon: 'trending_up',
    description: 'Окупаемость и рентабельность арендной недвижимости',
    component: 'RentalYieldCalc',
    color: 'positive',
    comingSoon: true,
  },
  {
    id: 'refinancing',
    title: 'Рефинансирование',
    icon: 'autorenew',
    description: 'Сравнение текущей и новой ипотечной программы',
    component: 'RefinancingCalc',
    color: 'orange',
    comingSoon: true,
  },
  {
    id: 'tax',
    title: 'Налоговый вычет',
    icon: 'savings',
    description: 'Расчет налогового вычета при покупке недвижимости',
    component: 'TaxCalc',
    color: 'purple',
    comingSoon: true,
  },
  {
    id: 'repair',
    title: 'Затраты на ремонт',
    icon: 'handyman',
    description: 'Планирование бюджета на ремонт недвижимости',
    component: 'RepairCalc',
    color: 'teal',
    comingSoon: true,
  },
]);
