export const demoEstates = [
  {
    active: 1,
    description: 'Через дорогу от метро, сдается за 25 тыс.',
    estate_type_icon: 'garage',
    estate_type_id: 3,
    estate_type_name: 'Гараж',
    id: 1,
    name: 'Гараж, ст.м. Ветеранов',
    recoupment: 38,
    user_id: 4,
  },
  {
    active: 1,
    description: null,
    estate_type_icon: 'weekend',
    estate_type_id: 1,
    estate_type_name: 'Квартира',
    id: 2,
    name: 'Квартира на Невском 50кв',
    recoupment: 18,
    user_id: 4,
  },
  {
    active: 1,
    description: '33 кв.м',
    estate_type_icon: 'weekend',
    estate_type_id: 1,
    estate_type_name: 'Квартира',
    id: 6,
    name: 'Квартира студия на Парнасе',
    recoupment: 77,
    user_id: 4,
  },
  {
    active: 1,
    description: 'Таунхаус с участком 10 соток',
    estate_type_icon: 'home',
    estate_type_id: 2,
    estate_type_name: 'Дом',
    id: 8,
    name: 'Дом на Озерках',
    recoupment: 29,
    user_id: 4,
  },
  {
    active: 1,
    description: null,
    estate_type_icon: 'yard',
    estate_type_id: 4,
    estate_type_name: 'Земельный участок',
    id: 9,
    name: 'Участок 50 соток в Пушкине',
    recoupment: 14,
    user_id: 4,
  },
  {
    active: 1,
    description: null,
    estate_type_icon: 'apartment',
    estate_type_id: 7,
    estate_type_name: 'Аппартаменты',
    id: 11,
    name: 'Апартаменты 1',
    recoupment: 92,
    user_id: 4,
  },
  {
    active: 1,
    description: null,
    estate_type_icon: 'local_convenience_store',
    estate_type_id: 8,
    estate_type_name: 'Коммерческое помещение',
    id: 12,
    name: 'Коммерческое помещение в ЖК Этажи',
    recoupment: 95,
    user_id: 4,
  },
  {
    active: 1,
    description: 'Семейное место на 2 авто',
    estate_type_icon: 'emoji_transportation',
    estate_type_id: 9,
    estate_type_name: 'Парковочное место',
    id: 13,
    name: 'Паркинг в ЖК Панорама',
    recoupment: 100,
    user_id: 4,
  },
];
